http:
    port: 3000
    
db:
    host: 'localhost'
    port: 5432
    username: 'backend_01_user'
    password: 'backend_01_pwd'
    database: 'backend_01_db'

doc:
    path: '/api'
    password: 'backend_01'
    title: 'backend_01 API'
    description: 'Official backend_01: Goods and Services API Documentation'
    version: '1.0'
    bearer:
        type: 'http'
        scheme: 'bearer'
        format: 'JWT'
        name: 'JWT'
        description: 'Enter Jason Web Token'
        in: 'header'
        reference: 'JWT-auth'

jwt:
    key: 'backend_01_jwtkey'
    alg: 'HS256'
    exp: '2h'

files:
    images:
        providers: '/home/iagarcia/Projects/Iagarcia/backend_01/uploads/'
        items: '/home/iagarcia/Projects/Iagarcia/backend_01/uploads/'
        requests: '/home/iagarcia/Projects/Iagarcia/backend_01/uploads/'
        clients: '/home/iagarcia/Projects/Iagarcia/backend_01/uploads/'
